services:
  npm:
    image: manjieqi/nginx-proxy-manager
    container_name: npm
    restart: unless-stopped
    depends_on:
      - geoip2
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 0.0.0.0:81:81
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - TZ=Asia/Shanghai
      - DISABLE_IPV6=true
    networks:
      - nginx

  geoip2:
    image: maxmindinc/geoipupdate
    container_name: geoip2
    restart: unless-stopped
    volumes:
      - ./data/geoip2:/usr/share/GeoIP
    environment:
      - TZ=Asia/Shanghai
      - GEOIPUPDATE_ACCOUNT_ID=******
      - GEOIPUPDATE_LICENSE_KEY=****************************************
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-City GeoLite2-Country GeoLite2-ASN'
      - GEOIPUPDATE_FREQUENCY=24
      - GEOIPUPDATE_PRESERVE_FILE_TIMES=1
    networks:
      - nginx

networks:
  nginx:
    external: true
